### ISSUE TITLE
Unauthorized Access Exception

### ISSUE THREAD

**Issue by mikebk** [blackducksoftware/hub-dotnet-binary-scan#5]
The first few times I tried to use the binary scanner, I received UnauthorizedAccess exceptions. There was a GUI popup plus command line information:
E:\blackduck\NetAssembliesScanner\Scanner.exe E:\blackduck\mbkTest\AspWeb\Web
Using settings in E:\blackduck\NetAssembliesScanner\scanner.ini
Please enter a username for the hub instance at https://xxxxxxxxxx
8443
yyyyyyyyy
Please enter the password for user  at the Hub instance at https://xxxxxxxxxxxxxxxxxx:8443
**********
Scanning E:\blackduck\mbkTest\AspWeb\Web...

Unhandled Exception: System.UnauthorizedAccessException: Access is denied. (Exce
ption from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence
)
   at System.Reflection.Assembly.LoadFile(String path)
   at Blackduck.Hub.Scanner.scanAssembly(String target)
   at Blackduck.Hub.Scanner.Main(String[] args)

I ran procmon to get a look at what going on. It's output (filtered by process name of scanner.exe) made me think running it from an administrave command prompt might help. 
![image](https://user-images.githubusercontent.com/34549950/34056713-1e08d8fc-e1a2-11e7-8934-15267137742e.png)

When I did that I started seeing this: 
![image](https://user-images.githubusercontent.com/34549950/34056750-45a32d9a-e1a2-11e7-9a6c-7e07ad8e9c43.png)

This happens now each time I run scanner from either the administrative or regular command prompts.

I tried using the compatibility troubleshooter but it didn't change the symptoms.

I'm doing this under Windows Server 2012 R2.

**Comment by yevster** [comment]
Is the file you're trying to scan located in a protected system directory (e.g. `C:\Program Files`, or `C:\windows`)?

**Comment by mikebk** [comment]
No, it's on a separate drive. I gave all users Write permissions to the directory structure with no change in symptoms.

**Comment by yevster** [comment]
@mikebk, so for one thing, with the released version, we can't be sure if the permissions issue is with the root binary you're trying to scan or one of its dependencies. 

I've improved handling of such errors. Could you run the latest build [(here)](https://ci.appveyor.com/project/yevster/hub-dotnet-binary-scan/build/artifacts) and send me any output or error messages you get?

**Comment by mikebk** [comment]
I copied my directory structure to a different server and found that the "This App can't run on your PC" message was happening, I extracted the files from the new build over the previous version and ran it. The "This App can't run on your PC" message wasn't shown. Instead I saw the following on the cmd prompt:

E:\blackduck\NetAssembliesScanner>scanner.exe "E:\blackduck\Apps\XXXX\XXXX_Build_4.6.36.3\Web"
Using settings in E:\blackduck\NetAssembliesScanner\scanner.ini
Please enter a username for the hub instance at https://blackduck.tsys.com
mblakeknox
Please enter the password for user  at the Hub instance at https://blackduck.tsys.com
**********
Scanning E:\blackduck\Apps\XXXX\XXXX_Build_4.6.36.3\Web...
Unable to examine Assembly: E:\blackduck\Apps\XXXX\XXXX_Build_4.6.36.3\Web. UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESS

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---
nderlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The
ccording to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Blackduck.Hub.HubUpload.authenticate(String baseUrl, String username, String password)
   at Blackduck.Hub.HubUpload.UploadScan(String baseUrl, String username, String password, ScannerJsonBuilder scanResult)
   at Blackduck.Hub.Scanner.Main(String[] args)

I wouldn't have expected an Assembly permission problem to have reported just the root folder.

I'm logged in as an administrator. Here are the properties of the Web folder: 
![image](https://user-images.githubusercontent.com/34549950/34181465-4006be38-e4e0-11e7-8b6d-9e5111d60ec3.png)

**Comment by yevster** [comment]
The argument can't be a folder, it must be a .NET executable or a DLL.

The .NET Binary scanner does not work like the traditional scanner. It loads a specific .NET assembly and then tries to load its dependencies.

**Comment by yevster** [comment]
The subsequent SSL/TLS exception likely has to do with an untrusted certificate signer on the hub side. To work around that issue, provide another argument for where to scan result, e.g. `scanner.exe C:\somepath\application.exe outputfile.json`. Then, in the Hub, go to the "Scans" screen, and select "Scan File" from the add menu. Then upload the output file that was created.

**Comment by mikebk** [comment]
Your absolutely right, there is a self signed certificate on the server. Can you put in more specific error text please?.
I ran the test again with the output file and got:

scanner.exe "E:\blackduck\Apps\XXXX\XXXX_Build_4.6.36.3\Web" XXXX_4.6.36.3-4.json
Scanning E:\blackduck\Apps\XXXX\XXXX_Build_4.6.36.3\Web...

Unhandled Exception: System.MissingMethodException: Method not found: 'Void Blackduck.Hub.ScannerJsonBuilder.AddScanProblem(System.String, System.Exception)'.
   at Blackduck.Hub.Scanner.scanAssembly(String target)
   at Blackduck.Hub.Scanner.Main(String[] args)

The folder with the .exe contains Newtonsoft.Json.dll and Newtonsoft.Json.xml. The working directory is the one with the .exe.

**Comment by yevster** [comment]
I see you're still trying to scan a directory (Web) instead of an executable or a DLL. As I described previously, that will not work.

Did you overwrite the prior scanner installation with the new build? It looks like one of the DLLs (`ScannerJson.dll`) did not get updated with the latest version. Could you completely obliterate your scanner directory and extract the latest build again?

You're right about the handling of the self-signed certificates on the Hub. I created a new issue (#6) to track concern, but let's resolve your problem first.

**Comment by mikebk** [comment]
It's an asp.net application which provides a few issues like what is the root assembly and then finding its .dll as .NET "randomizes" the .dll names.

And, it's Christmas.

Merry Christmas!

**Comment by yevster** [comment]
I'm afraid use case falls outside the scope of this particular scanner.

Consider using [Hub-Detect](https://github.com/blackducksoftware/hub-detect) instead. It won't trace down to any GAC dependencies you have (unless there's a package manifest containing them), but it should capture the signatures of everything in the Web directory. Please contact your Black Duck customer success representative if you require any assistance with Hub-Detect.

Merry Christmas to you too!
